spring:
  redis:
    port: 6379
    password: 1234
    host: 47.94.99.177
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 2000
  cache:
    type: redis
    cache-names: redisCache
server:
  port: 7890